# Generated by Django 2.0.4 on 2018-08-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'permissions': (('administrador', 'administrador'), ('cliente', 'cliente')),
            },
        ),
    ]
